# Generated by Django 3.2.5 on 2021-09-12 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('abstract', models.TextField()),
                ('img', models.ImageField(default='imageposts/images/default.jpg', upload_to='imageposts/images')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
