# Generated by Django 3.2.5 on 2022-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='img',
            field=models.ImageField(default='imageposts/imgs/default.jpg', upload_to='imageposts/imgs'),
        ),
    ]
