# Generated by Django 3.2.5 on 2022-04-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageposts', '0004_alter_imageposts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='img',
            field=models.ImageField(default='imageposts/static/imageposts/imgs/default.jpg', upload_to='imageposts/static/imageposts/imgs'),
        ),
    ]
