# Generated by Django 3.2.5 on 2022-04-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv',
            field=models.FileField(upload_to='static/query/csvs/'),
        ),
    ]
