prefix = 'projects/servir-e-sa/water_quality/'
linkaq = prefix+'modis/aqua'
linktr = prefix+'modis/terra'
linkl8 = prefix+'ls82'
links2 = prefix+'sentinel_2'

options = {
	'chl_modis_aq': {'display' : 'MODIS Aqua Chlorophyll',
					'link': linkaq,
					'index': 'chlor_a',
					'sensor': 'aqua',
					'platform':'modis'},
	'sd_modis_aq': {'display' :'MODIS Aqua Sechi Depth',
					'link': linkaq,
					'index': 'SD',
					'sensor': 'aqua',
					'platform':'modis'},
	'tsi_modis_aq': {'display' :'MODIS Aqua Trophic State Index',
					'link': linkaq,
					'index': 'TSI',
					'sensor': 'aqua',
					'platform':'modis'},
	'tsir_modis_aq': {'display' :'MODIS Aqua Trophic State Index Reclassified',
					'link': linkaq,
					'index': 'TSI_R',
					'sensor': 'aqua',
					'platform':'modis'},
	'chl_modis_tr': {'display' : 'MODIS Terra Chlorophyll',
					'link': linktr,
					'index': 'chlor_a',
					'sensor': 'terra',
					'platform':'modis'},
	'sd_modis_tr': {'display' :'MODIS Terra Sechi Depth',
					'link': linktr,
					'index': 'SD',
					'sensor': 'terra',
					'platform':'modis'},
	'tsi_modis_tr': {'display' :'MODIS Terra Trophic State Index',
					'link': linktr,
					'index': 'TSI',
					'sensor': 'terra',
					'platform':'modis'},
	'tsir_modis_tr': {'display' :'MODIS Terra Trophic State Index Reclassified',
					'link': linktr,
					'index': 'TSI_R',
					'sensor': 'terra',
					'platform':'modis'},
	'chl_sen2': {'display' : 'Sentinel 2 Chlorophyll',
					'link': links2,
					'index': 'chlor_a',
					'sensor': '2',
					'platform':'sentinel'},
	'sd_sen2': {'display' :'Sentinel 2 Sechi Depth',
					'link': links2,
					'index': 'SD',
					'sensor': '2',
					'platform':'sentinel'},
	'tsi_sen2': {'display' :'Sentinel 2 Trophic State Index',
					'link': links2,
					'index': 'TSI',
					'sensor': '2',
					'platform':'sentinel'},
	'tsir_sen2': {'display' :'Sentinel 2 Trophic State Index Reclassified',
					'link': links2,
					'index': 'TSI_R',
					'sensor': '2',
					'platform':'sentinel'},
	'chl_ls8': {'display' : 'Landsat 8 Chlorophyll',
					'link': linkl8,
					'index': 'chlor_a',
					'sensor': '8',
					'platform':'landsat'},
	'sd_ls8': {'display' :'Landsat 8 Sechi Depth',
					'link': linkl8,
					'index': 'SD',
					'sensor': '8',
					'platform':'landsat'},
	'tsi_ls8': {'display' :'Landsat 8 Trophic State Index',
					'link': linkl8,
					'index': 'TSI',
					'sensor': '8',
					'platform':'landsat'},
	'tsir_ls8': {'display' :'Landsat 8 Trophic State Index Reclassified',
					'link': linkl8,
					'index': 'TSI_R',
					'sensor': '8',
					'platform':'landsat'},
}