# Generated by Django 3.2.5 on 2021-09-11 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='slider/images/default.jpg', upload_to='slider/images')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=70)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
            ],
        ),
    ]
