# Generated by Django 3.2.5 on 2021-09-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(default='static/slider/images/default.jpg', upload_to='static/slider/images'),
        ),
    ]
