# Generated by Django 3.2.5 on 2022-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0006_alter_slider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(default='slider/imgs/default.jpg', upload_to='slider/imgs'),
        ),
    ]
